name: thoughts
description: Project to keept track of thoughts
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rename: ^2.1.1

  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.4

  provider: ^6.0.5
  velocity_x: ^4.1.1
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.0
  google_sign_in: ^6.1.4
  uuid: ^3.0.7
  cached_network_image: ^3.2.3
  dynamic_color: ^1.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
